// Filename: colladaNode.I
// Created by: Xidram (15Apr10)
//
////////////////////////////////////////////////////////////////////
//
// PANDA 3D SOFTWARE
// Copyright (c) Carnegie Mellon University.  All rights reserved.
//
// All use of this software is subject to the terms of the revised BSD
// license.  You should have received a copy of this license along
// with this source code in a file named "LICENSE."
//
////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////
//     Function: ColladaNode::clear
//       Access: Public
//  Description: Resets the ColladaNode to its initial state.
////////////////////////////////////////////////////////////////////
INLINE void ColladaNode::
clear() {
  ColladaAssetElement::clear();
}

