#include "colladaAsset.cxx"
#include "colladaCamera.cxx"
#include "colladaContributor.cxx"
#include "colladaDocument.cxx"
#include "colladaEffect.cxx"
#include "colladaGeometry.cxx"
#include "colladaLight.cxx"
#include "colladaMaterial.cxx"
#include "colladaMesh.cxx"
#include "colladaNode.cxx"
#include "colladaOptics.cxx"
#include "colladaProfile.cxx"
#include "colladaVisualScene.cxx"
#include "config_collada.cxx"
#include "load_collada_file.cxx"
#include "loaderFileTypeDae.cxx"

