#include "colladaAsset.cxx"
#include "colladaContributor.cxx"
#include "colladaData.cxx"
#include "colladaEffect.cxx"
#include "colladaGeometry.cxx"
#include "colladaLoader.cxx"
#include "colladaMesh.cxx"
#include "colladaNode.cxx"
#include "colladaVisualScene.cxx"
#include "config_collada.cxx"
#include "load_collada_file.cxx"
#include "loaderFileTypeDae.cxx"

