// Filename: physxControllerDesc.I
// Created by:  enn0x (22Sep09)
//
////////////////////////////////////////////////////////////////////
//
// PANDA 3D SOFTWARE
// Copyright (c) Carnegie Mellon University.  All rights reserved.
//
// All use of this software is subject to the terms of the revised BSD
// license.  You should have received a copy of this license along
// with this source code in a file named "LICENSE."
//
////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////
//     Function: PhysxControllerDesc::Constructor
//       Access: Published
//  Description:
////////////////////////////////////////////////////////////////////
INLINE PhysxControllerDesc::
PhysxControllerDesc() {

}

////////////////////////////////////////////////////////////////////
//     Function: PhysxControllerDesc::Constructor
//       Access: Public
//  Description:
////////////////////////////////////////////////////////////////////
/*
TODO: factory, create object depending on desc.getType()...

INLINE PhysxControllerDesc::
PhysxControllerDesc(NxControllerDesc &desc) : _desc(desc) {

}
*/

////////////////////////////////////////////////////////////////////
//     Function: PhysxControllerDesc::Destructor
//       Access: Published
//  Description:
////////////////////////////////////////////////////////////////////
INLINE PhysxControllerDesc::
~PhysxControllerDesc() {

}

