#include "config_physx.cxx"
#include "physxManager.cxx"
#include "physxActor.cxx"
#include "physxActorDesc.cxx"
#include "physxBodyDesc.cxx"
#include "physxBoxShapeDesc.cxx"
#include "physxCapsuleShapeDesc.cxx"
#include "physxPlaneShapeDesc.cxx"
#include "physxScene.cxx"
#include "physxSceneDesc.cxx"
#include "physxShapeDesc.cxx"
#include "physxSphereShapeDesc.cxx"

#include "physxObject.cxx"
